spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: activitydb
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 8081

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true