spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ai-database
server:
  port: 8083

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}



