spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5500/postgres
    username: postgres
    password: khush?28
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
